# Generated by Django 6.0.5 on 2026-06-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
