# Generated by Django 6.0.5 on 2026-06-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('program', models.CharField(choices=[('B.E. Computer Engineering', 'B.E. Computer Engineering'), ('B.E. Electrical Engineering', 'B.E. Electrical Engineering'), ('B.E. Mechanical Engineering', 'B.E. Mechanical Engineering'), ('B.E. Civil Engineering', 'B.E. Civil Engineering'), ('B.E. Electronics & Telecom', 'B.E. Electronics & Telecom'), ('B.E. Chemical Engineering', 'B.E. Chemical Engineering'), ('M.E. Computer Engineering', 'M.E. Computer Engineering'), ('M.E. Mechanical Engineering', 'M.E. Mechanical Engineering'), ('M.E. Electrical Engineering', 'M.E. Electrical Engineering'), ('M.E. Electronics & Telecom', 'M.E. Electronics & Telecom')], max_length=100)),
                ('tenth_percentage', models.FloatField()),
                ('twelfth_percentage', models.FloatField()),
                ('entrance_score', models.FloatField(blank=True, null=True)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewing', 'Reviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
