# Generated by Django 6.0.5 on 2026-06-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_admissionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
