# Generated by Django 6.0.5 on 2026-06-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='prn_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='tenth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='twelfth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
    ]
