# Generated by Django 6.0.5 on 2026-06-07 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_studentaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='tenth_marksheet',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='twelfth_marksheet',
        ),
        migrations.CreateModel(
            name='SemesterMarksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8')], max_length=20)),
                ('marksheet', models.FileField(upload_to='marksheets/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='registration.admissionapplication')),
            ],
        ),
    ]
